name: msys2 build
# https://stackoverflow.com/a/75758843

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: gcc version
      run: gcc --version
    - name: Build
      run: make -C RunCPM msys2 build
    - name: Copy binary to artifact folder
      run: cp RunCPM/RunCPM.exe output

